### ISSUE TITLE
README.md should be pure english

### ISSUE THREAD

**Issue by mcm1957** [crycode-de/ioBroker.odl#105]
Please consider moving the german parts of README.md to a seperate file, typically located at doc/*. Bute a README_de.ms is also OK. And of course a link from main README.md to the language specifc file is ok.

README.md is automatically translated for ioBroker Web pages. Multiple langugaes consfuse this process.

**Comment by crycode-de** [comment]
The adapter in mainly intended for German users (as the provided data is from Germany).
So my intension was to describe the adapter for the German users directly in the main readme file.

Of course I understand that this might be confusing for auto translate.
If there is a `README_de.md` file, will this be used instead of the automatic translation?

Also a nice to have would be some kind of marking parts of the readme to be not automatically translated.
Maybe using something like this:
```md
Some description
<!--autotranslate off-->
Something not to translate
<!--autotranslate on-->
Some more description
```

**Comment by mcm1957** [comment]
Please remove german parts from README.md and i.e. mode to README_de.md or some other documentatioon file located at /doc.

**Comment by mcm1957** [comment]
> The adapter in mainly intended for German users (as the provided data is from Germany). So my intension was to describe the adapter for the German users directly in the main readme file.
> 
> Of course I understand that this might be confusing for auto translate. If there is a `README_de.md` file, will this be used instead of the automatic translation?

Please contact @Apollon77 or @Bluefox at Telegramm channel (invites at www.iobroker.dev) to discuss these details. As far as I know the common.docs section at io-package.json should be used for this
https://github.com/ioBroker/ioBroker.js-controller/blob/44c6d25d45257b10665d083848063b97fc16b679/schemas/io-package.json#L853
